"""add_source_branch_column_to_feature_branch

Revision ID: 0d75a43db713
Revises: c9055653d471
Create Date: 2024-11-22 16:31:56.170417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d75a43db713'
down_revision: Union[str, None] = 'c9055653d471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_requests', sa.Column('source_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('feature_requests', 'git_repo_remote_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feature_requests', 'git_repo_local_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('feature_requests', 'feature_branch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feature_requests', 'feature_branch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feature_requests', 'git_repo_local_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('feature_requests', 'git_repo_remote_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('feature_requests', 'source_branch')
    # ### end Alembic commands ###
