"""add_git_columns_to_feature_requests

Revision ID: c9055653d471
Revises: c87649763767
Create Date: 2024-11-22 16:14:27.870280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c9055653d471'
down_revision: Union[str, None] = 'c87649763767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_requests', sa.Column('git_repo_local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('feature_requests', sa.Column('git_repo_remote_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('feature_requests', sa.Column('feature_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_requests', 'feature_branch')
    op.drop_column('feature_requests', 'git_repo_remote_url')
    op.drop_column('feature_requests', 'git_repo_local_path')
    # ### end Alembic commands ###
